inherit_from: configs/TUM_RGBD/tum.yaml
frame_lims: [370, 470]
frame_rate: 10
verbose: False
occupancy: False
mapping:
  bound: [[-1.5,1.5],[-1.5,1.5],[-1.5, 1.5]]
  marching_cubes_bound: [[-2.,2.],[-2.,2.],[-2., 2.]]
  vis_freq: 10
  vis_inside_freq: 1000
  pixels: 1000
  iters_first: 300
  iters: 100
tracking:
  vis_freq: 1000
  vis_inside_freq: 1000
  pixels: 200
  seperate_LR: False
  gt_camera : True
data:
  input_folder: Datasets/TUM_RGBD/rgbd_dataset_freiburg2_rpy
  output: output/TUM_RGBD/rgbd_dataset_freiburg2_rpy
cam:  #intrinsic is different per scene in TUM
  H: 480 
  W: 640 
  fx: 520.9
  fy: 521.0
  cx: 325.1
  cy: 249.7
  crop_edge: 8
  crop_size: [384,512]
  distortion: [0.2312, -0.7849, -0.0033, -0.0001, 0.9172]
